name: splitcat
description: "Split and merge files easy way."
publish_to: 'none'
version: 0.1.0

environment:
  flutter: ">=3.24.0"
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.2
  logger: ^2.4.0
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
