name: splitcat
description: "Split and merge files easy way."
publish_to: 'none'
version: 0.1.8

environment:
  flutter: ">=3.24.0"
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: "8.1.2"
  file_selector: "1.0.3"
  gtk: "2.1.0"
  logger: ^2.4.0
  window_manager: ^0.4.2
  xdg_directories: 1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: 5.7.0

flutter:
  uses-material-design: true
  assets:
    - linux/flutter/assets/icons/16x16/icon.png
    - linux/flutter/assets/icons/32x32/icon.png
    - linux/flutter/assets/icons/64x64/icon.png
    - linux/flutter/assets/icons/128x128/icon.png
    - linux/flutter/assets/icons/256x256/icon.png
flutter_gen:
  line_length: 150
