name: splitcat
description: "Split and merge files easy way."
publish_to: 'none'
version: 0.1.17+18

environment:
  flutter: ">=3.24.0"
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  file_picker: "8.1.2"
  file_selector: "1.0.3"
  gtk: "2.1.0"
  logger: ^2.4.0
  window_manager: ^0.4.2
  xdg_directories: 1.0.4
  url_launcher: ^6.0.9
  flutter_archive: ^6.0.3
  archive: ^3.3.0
  path_provider: ^2.0.14
  share_plus: ^10.1.0
  share_plus_dialog: ^2.0.1
  path: ^1.9.0
  package_info_plus: ^8.1.0
  encrypt: ^5.0.3
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: 5.7.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - linux/flutter/assets/icons/16x16/icon.png
    - linux/flutter/assets/icons/32x32/icon.png
    - linux/flutter/assets/icons/64x64/icon.png
    - linux/flutter/assets/icons/128x128/icon.png
    - linux/flutter/assets/icons/256x256/icon.png
flutter_gen:
  line_length: 150
