name: splitcat
description: "Split and merge files easy way."
publish_to: 'none'
version: 0.1.1

environment:
  flutter: ">=3.13.9"
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ">=8.0.0 <9.0.0"
  logger: ^2.4.0
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: 5.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/16x16
    - assets/icons/32x32
    - assets/icons/64x64
    - assets/icons/128x128
    - assets/icons/256x256
flutter_gen:
  line_length: 150
