display_name: Splitcat
package_name: splitcat
maintainer:
  name: Vogonwann
  email: ivan@janjic.lol
priority: optional
section: x11
installed_size: 30600
essential: false
icon: assets/icons/256x256/icon.png

pre_dependencies:
  - libc6 (>= 2.31)

dependencies:
  - libappindicator3-1 | libayatana-appindicator3-1
  - gir1.2-appindicator3-0.1 | gir1.2-ayatanaappindicator3-0.1
  - libayatana-ido3-0.4-0
  - xdg-user-dirs

postinstall_scripts:
  - echo "Installed Splitcat successfully"
postuninstall_scripts:
  - echo "Sorry to see you go :("

keywords:
  - Files
  - Data
  - Tools
  - Split
  - Merge

generic_name: An open source cross-platform tool for spliting and merging files

categories:
  - GTK
  - FileTools
  - Utility

startup_notify: true