name: Windows test

on:
  workflow_dispatch:

jobs:
  build_windows_zip_x86_64:
    needs: [build, create_release]

    runs-on: windows-latest
    
    steps:
    - name: Fix long file paths
      run: git config --system core.longpaths true

    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: "stable"
    
    - name: Clean previous builds
      run: flutter clean

    - name: Show current dir
      run: pwd

    - name: List current dir
      run: ls windows

    - name: Dependencies
      working-directory: ./
      run: flutter pub get

    - name: Compile for Windows
      working-directory: ./
      run: flutter build windows --release --verbose

    - name: Create empty settings.json
      working-directory: ./
      run: |
            if (-Not (Test-Path -Path D:\a\splitcat\splitcat\build\windows\runner\Release)) {
                New-Item -ItemType Directory -Path D:\a\splitcat\splitcat\build\windows\runner\Release
            }
            echo {} > D:\a\splitcat\splitcat\build\windows\runner\Release\settings.json

    - name: List DLL files
      run: ls scripts/windows/x64/

    - name: Add DLL files
      working-directory: ./
      run: |
            Copy-Item scripts/windows/x64/msvcp140.dll D:\a\splitcat\splitcat\build\windows\runner\Release\
            Copy-Item scripts/windows/x64/vcruntime140.dll D:\a\splitcat\splitcat\build\windows\runner\Release\
            Copy-Item scripts/windows/x64/vcruntime140_1.dll D:\a\splitcat\splitcat\build\windows\runner\Release\

    - name: Zip compiled files
      working-directory: app
      run: Compress-Archive -Path ../build/windows/runner/Release/* -DestinationPath LocalSend.zip

    - name: Check if ZIP file exists
      run: ls app/

    - name: Upload ZIP file
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: app/LocalSend.zip
        asset_name: windows-zip-x86-64-result
        asset_content_type: application/zip
    
