name: Windows test

on:
  workflow_dispatch:

jobs:
  build_windows_zip_x86_64:

    runs-on: windows-latest

    steps:
    - name: Fix long file paths
      run: git config --system core.longpaths true

    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: "stable"

    - name: Dependencies
      working-directory: ./
      run: flutter pub get

    - name: Compile for Windows
      working-directory: ./
      run: flutter build windows --release

    - name: Print working dir
      run: pwd

    - name: List working dir
      run: ls

    - name: Create empty settings.json
      working-directory: ./
      run: echo {} > D:\a\splitcat\splitcat\build\windows\runner\Release\settings.json

    - name: Add DLL files
      working-directory: ./
      run: |
            Copy-Item ../scripts/windows/x64/msvcp140.dll build/windows/runner/Release/
            Copy-Item ../scripts/windows/x64/vcruntime140.dll build/windows/runner/Release/
            Copy-Item ../scripts/windows/x64/vcruntime140_1.dll build/windows/runner/Release/

    - name: Zip compiled files
      working-directory: ./
      run: Compress-Archive -Path build/windows/runner/Release/* -DestinationPath Splitcat.zip

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: windows-zip-x86-64-result
        path: Splitcat.zip
    
